### ISSUE TITLE
bug: specific license for each files if apply? for packaging and distribute

### ISSUE THREAD

**Issue by mckaygerhard** [LordShenron/Project-Ignite#2]
i plan to package and distribute, there's any limitation on?

i can see the GPLv2 license, but there's some files that are not apply this license?

thanks in advance!

**Comment by LordShenron** [comment]
Yes, you can package and distribute, there's no limitation.
That GPLv2 license is valid on all files, while distributing maintain the package specific license too.
And sorry, if i am little in addressing your issue. Hope you don't mind.

**Comment by mckaygerhard** [comment]
> And sorry, if i am little in addressing your issue. Hope you don't mind.

I asked due if there was any file that could be taken from another project or person and that does not have any specified license, if this is the case I need to know which, if not, would not apply and i'll close the issue

**Comment by mckaygerhard** [comment]
> And sorry, if i am little in addressing your issue. Hope you don't mind.

@LordShenron I asked due if there was any file that could be taken from another project or person and that does not have any specified license, if this is the case I need to know which, if not, would not apply and i'll close the issue

**Comment by LordShenron** [comment]
GPL v2 is applied on every package.

**Comment by mckaygerhard** [comment]
umm ok thanks i'll close this issue, assume that all files are original created by you now and licenced under GPLv2.. i'll post later a link to deb packages and rpm packages in opensuse build.
